New log file opened at Mon Oct 19 09:30:11 CEST 2015 by 8440@Obsidian
Taking next connection to: 50378
New client attempting to connect on port: 50379-50378
  Address = /192.168.178.14:50378
This client on port 50379 has uuid d9b0875d-d5f2-4b62-9e40-903e2d5c03b4 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-d9b0875d-d5f2-4b62-9e40-903e2d5c03b4
Taking next connection to: 50378
New client attempting to connect on port: 50380-50378
  Address = /192.168.178.14:50378
Handshake exception on socket: 50380
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 50378
New client attempting to connect on port: 50381-50378
  Address = /192.168.178.14:50378
This client on port 50381 has uuid d59f660a-30b5-473d-aa14-c7cd0a9ea0e2 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-d9b0875d-d5f2-4b62-9e40-903e2d5c03b4, activator-d59f660a-30b5-473d-aa14-c7cd0a9ea0e2
Taking next connection to: 50378
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 50378
New client attempting to connect on port: 50527-50378
  Address = /192.168.178.14:50378
Handshake exception on socket: 50527
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 50378
New client attempting to connect on port: 50528-50378
  Address = /192.168.178.14:50378
This client on port 50528 has uuid ef78b2ce-74b7-4648-8186-b11c674456e0 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-d59f660a-30b5-473d-aa14-c7cd0a9ea0e2, play-fork-run-ef78b2ce-74b7-4648-8186-b11c674456e0
Taking next connection to: 50378
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 50378
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 50378
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 50378
